In [1]:
import pandas as pd
import scipy.stats as stats

In [2]:
import os

os.chdir(r"C:\Users\mf_gu\OneDrive\Documentos\Projetos\Projeto Ecommerce\ecommerce-joias")

In [3]:
#criando os dfs
df_carrinhos = pd.read_csv("_data\clean\e_commerce_carrinhos.csv")
df_clientes = pd.read_csv("_data\clean\e_commerce_clientes.csv")
df_pedidos = pd.read_csv("_data\clean\e_commerce_pedidos.csv")

In [4]:
#analise de tipos
print(df_pedidos.dtypes)

#vendo colunas
print(df_pedidos.columns)

Unnamed: 0             int64
id                     int64
data                  object
data_pagamento        object
data_cancelamento     object
numero_pedido          int64
status                object
pagamento             object
produto               object
sku                   object
quantidade             int64
total                 object
total_pago            object
total_produtos        object
total_desconto       float64
total_custo            int64
total_juros          float64
total_frete           object
total_item            object
parcelado             object
parcelamento           int64
entregue              object
dias_para_entrega      int64
data_de_entrega       object
entrega_bairro        object
entrega_cidade        object
entrega_estado        object
entrega_cep           object
utm_source            object
utm_campaign          object
utm_medium            object
utm_content           object
utm_term              object
customizacao         float64
id_cliente            object
dtype: object
Index(['Unnamed: 0', 'id', 'data', 'data_pagamento', 'data_cancelamento',
       'numero_pedido', 'status', 'pagamento', 'produto', 'sku', 'quantidade',
       'total', 'total_pago', 'total_produtos', 'total_desconto',
       'total_custo', 'total_juros', 'total_frete', 'total_item', 'parcelado',
       'parcelamento', 'entregue', 'dias_para_entrega', 'data_de_entrega',
       'entrega_bairro', 'entrega_cidade', 'entrega_estado', 'entrega_cep',
       'utm_source', 'utm_campaign', 'utm_medium', 'utm_content', 'utm_term',
       'customizacao', 'id_cliente'],
      dtype='object')

In [5]:
df_pedidos.head()

,Unnamed: 0,id,data,data_pagamento,data_cancelamento,numero_pedido,status,pagamento,produto,sku,...,entrega_cidade,entrega_estado,entrega_cep,utm_source,utm_campaign,utm_medium,utm_content,utm_term,customizacao,id_cliente
0,1,117569438,04/08/2024 18:26:40,04/08/2024 18:27,NaN,1042552530523300,Pagamento aprovado,Pix,BRACELETE AJUSTÁVEL O COM COROA,DFREFSP8P,...,Brasilia,Distrito Federal,72455490,NaN,NaN,NaN,NaN,NaN,NaN,31d69aed10
1,2,117385907,01/08/2024 19:08:02,01/08/2024 19:11,NaN,1042552893870166,Pagamento aprovado,Pix,BRACELETE AJUSTÁVEL O COM COROA,DFREFSP8P,...,Varzea Nova(Santa Rita),Paraiba,58304500,NaN,NaN,NaN,NaN,NaN,NaN,3e109eedd5
2,3,117385794,01/08/2024 19:05:53,NaN,01/08/2024 19:12,1042552190094688,Cancelado,Pix,BRACELETE AJUSTÁVEL O COM COROA,DFREFSP8P,...,Varzea Nova(Santa Rita),Paraiba,58304500,NaN,NaN,NaN,NaN,NaN,NaN,3e109eedd5
3,4,117382873,01/08/2024 18:12:14,NaN,01/08/2024 19:13,1042552273445602,Cancelado,Pix,BRACELETE AJUSTÁVEL O COM COROA,DFREFSP8P,...,Varzea Nova(Santa Rita),Paraiba,58304500,NaN,NaN,NaN,NaN,NaN,NaN,3e109eedd5
4,5,117382771,01/08/2024 18:09:41,NaN,01/08/2024 19:13,1042552782939597,Cancelado,Pix,BRACELETE AJUSTÁVEL O COM COROA,DFREFSP8P,...,Varzea Nova(Santa Rita),Paraiba,58304500,NaN,NaN,NaN,NaN,NaN,NaN,3e109eedd5

In [6]:
#convertendo data - str > datetime
df_pedidos['data'] = pd.to_datetime(df_pedidos['data'], format='%d/%m/%Y %H:%M:%S')

In [7]:
#obter apenas data, sem time
df_pedidos['data_aux'] = pd.to_datetime(df_pedidos['data']).dt.date

In [8]:
# Agrupar por ID do pedido e obter a primeira ocorrência de cada data para cada pedido
df_pedidos_unicos = df_pedidos.groupby('id').first().reset_index()

# Contar pedidos por data
contagem_por_data = df_pedidos_unicos.groupby('data_aux').size().reset_index(name='contagem')

# Ordenar pela contagem em ordem decrescente
print(contagem_por_data.sort_values('contagem', ascending=False))

      data_aux  contagem
31  2024-08-01         8
17  2024-06-17         8
0   2024-05-22         6
1   2024-05-23         5
13  2024-06-13         5
5   2024-06-01         4
23  2024-07-09         4
18  2024-06-18         3
12  2024-06-12         3
26  2024-07-16         3
21  2024-07-07         2
28  2024-07-26         2
27  2024-07-17         2
7   2024-06-03         2
11  2024-06-11         2
4   2024-05-29         2
3   2024-05-26         1
16  2024-06-16         1
15  2024-06-15         1
14  2024-06-14         1
9   2024-06-07         1
10  2024-06-08         1
2   2024-05-24         1
6   2024-06-02         1
8   2024-06-04         1
24  2024-07-10         1
22  2024-07-08         1
19  2024-06-25         1
20  2024-07-03         1
25  2024-07-14         1
29  2024-07-27         1
30  2024-07-29         1
32  2024-08-04         1

In [9]:
#criando nova coluna - dia da semana
df_pedidos['dia_semana'] = df_pedidos['data'].dt.day_name()

df_pedidos.head()

,Unnamed: 0,id,data,data_pagamento,data_cancelamento,numero_pedido,status,pagamento,produto,sku,...,entrega_cep,utm_source,utm_campaign,utm_medium,utm_content,utm_term,customizacao,id_cliente,data_aux,dia_semana
0,1,117569438,2024-08-04 18:26:40,04/08/2024 18:27,NaN,1042552530523300,Pagamento aprovado,Pix,BRACELETE AJUSTÁVEL O COM COROA,DFREFSP8P,...,72455490,NaN,NaN,NaN,NaN,NaN,NaN,31d69aed10,2024-08-04,Sunday
1,2,117385907,2024-08-01 19:08:02,01/08/2024 19:11,NaN,1042552893870166,Pagamento aprovado,Pix,BRACELETE AJUSTÁVEL O COM COROA,DFREFSP8P,...,58304500,NaN,NaN,NaN,NaN,NaN,NaN,3e109eedd5,2024-08-01,Thursday
2,3,117385794,2024-08-01 19:05:53,NaN,01/08/2024 19:12,1042552190094688,Cancelado,Pix,BRACELETE AJUSTÁVEL O COM COROA,DFREFSP8P,...,58304500,NaN,NaN,NaN,NaN,NaN,NaN,3e109eedd5,2024-08-01,Thursday
3,4,117382873,2024-08-01 18:12:14,NaN,01/08/2024 19:13,1042552273445602,Cancelado,Pix,BRACELETE AJUSTÁVEL O COM COROA,DFREFSP8P,...,58304500,NaN,NaN,NaN,NaN,NaN,NaN,3e109eedd5,2024-08-01,Thursday
4,5,117382771,2024-08-01 18:09:41,NaN,01/08/2024 19:13,1042552782939597,Cancelado,Pix,BRACELETE AJUSTÁVEL O COM COROA,DFREFSP8P,...,58304500,NaN,NaN,NaN,NaN,NaN,NaN,3e109eedd5,2024-08-01,Thursday

In [10]:
# Agrupar por ID do pedido e obter a primeira ocorrência de cada data para cada pedido
df_pedidos_unicos = df_pedidos.groupby('id').first().reset_index()

# Agrupar por 'dia_semana' e contar o número de pedidos únicos
contagem_por_dia = df_pedidos_unicos.groupby('dia_semana').size().reset_index(name='contagem')

# Ordenar a contagem em ordem decrescente
print(contagem_por_dia.sort_values('contagem', ascending=False))

  dia_semana  contagem
4   Thursday        18
6  Wednesday        15
5    Tuesday        14
1     Monday        12
2   Saturday         7
3     Sunday         7
0     Friday         5

In [11]:
# Frequência esperada se os pedidos fossem uniformemente distribuídos
frequencia_esperada = len(df_pedidos_unicos) / 7

print(frequencia_esperada)

11.142857142857142

In [12]:
# Extrair a lista de contagens observadas e a lista de dias da semana
contagens_observadas = contagem_por_dia['contagem']
dias_da_semana = contagem_por_dia['dia_semana']

# Calcular a frequência esperada (assumindo uma distribuição uniforme)
frequencia_esperada = contagens_observadas.sum() / len(dias_da_semana)
frequencias_esperadas = [frequencia_esperada] * len(dias_da_semana)

# Realizar o teste qui-quadrado
chi2, p_valor = stats.chisquare(contagens_observadas, f_exp=frequencias_esperadas)

# Exibir os resultados
print(f"Estatística qui-quadrado: {chi2}")
print(f"Valor-p: {p_valor}")

Estatística qui-quadrado: 12.820512820512823
Valor-p: 0.045976432442388006

In [13]:
if p_valor < 0.05:
    print("Rejeitamos a hipótese nula: há evidência de sazonalidade nos dias da semana.")
else:
    print("Não rejeitamos a hipótese nula: não há evidência de sazonalidade nos dias da semana.")

Rejeitamos a hipótese nula: há evidência de sazonalidade nos dias da semana.